/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author anees
 */
public class Login extends javax.swing.JFrame {

   
    public Login() {
        initComponents();
        Login.setBorder(BorderFactory.createLineBorder(Color.black));
        lbl_U.setVisible(false);
        lbl_p.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        admin_un = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        admin_pw = new javax.swing.JPasswordField();
        lbl_U = new javax.swing.JLabel();
        lbl_p = new javax.swing.JLabel();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(444, 395));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-admin-settings-male-30.png"))); // NOI18N
        jLabel1.setText("Admin Login");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 30, 150, 30);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Username:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 120, 72, 21);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(49, 200, 70, 21);

        admin_un.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        admin_un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_unActionPerformed(evt);
            }
        });
        admin_un.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                admin_unKeyPressed(evt);
            }
        });
        jPanel1.add(admin_un);
        admin_un.setBounds(150, 120, 180, 30);

        Login.setBackground(new java.awt.Color(153, 153, 255));
        Login.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Login.setForeground(new java.awt.Color(102, 102, 255));
        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-login-24.png"))); // NOI18N
        Login.setText("Login");
        Login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Login.setBorderPainted(false);
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginMouseExited(evt);
            }
        });
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login);
        Login.setBounds(80, 280, 110, 60);

        admin_pw.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        admin_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_pwActionPerformed(evt);
            }
        });
        admin_pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                admin_pwKeyPressed(evt);
            }
        });
        jPanel1.add(admin_pw);
        admin_pw.setBounds(150, 200, 180, 30);

        lbl_U.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbl_U.setText("*");
        jPanel1.add(lbl_U);
        lbl_U.setBounds(330, 110, 10, 26);

        lbl_p.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbl_p.setText("*");
        jPanel1.add(lbl_p);
        lbl_p.setBounds(330, 190, 10, 26);

        close.setBackground(new java.awt.Color(153, 153, 255));
        close.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        close.setForeground(new java.awt.Color(102, 102, 255));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-close-window-30.png"))); // NOI18N
        close.setText("Close");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(220, 280, 120, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admin_unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_unActionPerformed
       
    }//GEN-LAST:event_admin_unActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
     
        lbl_U.setVisible(false);
        lbl_p.setVisible(false);
        if(admin_un.getText().equals(""))
        {
            lbl_U.setVisible(true);
        }
        if(String.valueOf(admin_pw.getPassword()).equals(""))
        {
            lbl_p.setVisible(true);
        }
        PreparedStatement st;
        ResultSet rs;
        
        String username= admin_un.getText();
        String password= String.valueOf(admin_pw.getPassword());
        
        String query= "SELECT * FROM `login` WHERE `Username` = ? AND `Password`= ?";
        try {
            st=MyConnection.getConnection().prepareStatement(query);
            
            st.setString(1, username);
            st.setString(2, password);
            
            rs=st.executeQuery();
            
            if(rs.next()){
                Homepage form= new Homepage();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                this.dispose();
                }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Username/Password", "Login Error", 2);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void admin_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_pwActionPerformed

        lbl_U.setVisible(false);
        lbl_p.setVisible(false);
        if(admin_un.getText().equals(""))
        {
            lbl_U.setVisible(true);
        }
        if(String.valueOf(admin_pw.getPassword()).equals(""))
        {
            lbl_p.setVisible(true);
        }
        PreparedStatement st;
        ResultSet rs;
        
        String username= admin_un.getText();
        String password= String.valueOf(admin_pw.getPassword());
        
        String query= "SELECT * FROM `login` WHERE `Username` = ? AND `Password`= ?";
        try {
            st=MyConnection.getConnection().prepareStatement(query);
            
            st.setString(1, username);
            st.setString(2, password);
            
            rs=st.executeQuery();
            
            if(rs.next()){
                Homepage form= new Homepage();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                this.dispose();
                }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Username/Password", "Login Error", 2);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
     
    }//GEN-LAST:event_admin_pwActionPerformed

    private void LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseEntered
        Login.setBackground(new Color(102,102,255));
        Login.setForeground(new Color(153,153,255));
    }//GEN-LAST:event_LoginMouseEntered

    private void LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseExited
        Login.setBackground(new Color(153,153,255));
        Login.setForeground(new Color(102,102,255));
    }//GEN-LAST:event_LoginMouseExited

    private void admin_unKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_unKeyPressed
        
    }//GEN-LAST:event_admin_unKeyPressed

    private void admin_pwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_pwKeyPressed
       
    }//GEN-LAST:event_admin_pwKeyPressed

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setBackground(new Color(102,102,255));
        close.setForeground(new Color(153,153,255));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setBackground(new Color(153,153,255));
        close.setForeground(new Color(102,102,255));
    }//GEN-LAST:event_closeMouseExited

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JPasswordField admin_pw;
    private javax.swing.JTextField admin_un;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_U;
    private javax.swing.JLabel lbl_p;
    // End of variables declaration//GEN-END:variables
}
