/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym;

import java.awt.Color;
import java.awt.Font;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author anees
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        fillmembername();
        PayTable.getTableHeader().setFont(new Font("Comic Sans MS",Font.BOLD,14));
        PayTable.getTableHeader().setOpaque(false);
        PayTable.getTableHeader().setBackground(new Color(153,153,255));
        PayTable.getTableHeader().setForeground(new Color(102,102,255));
        this.setLocationRelativeTo(null);
    }
    
    Bill c=new Bill();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Pay_date = new com.toedter.calendar.JDateChooser();
        prod_price = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mbrn = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        total_amt = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PayTable = new javax.swing.JTable();
        View = new javax.swing.JButton();
        pack_amt = new javax.swing.JTextField();
        Prod_price = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        valid_upto = new com.toedter.calendar.JDateChooser();
        bill = new javax.swing.JButton();
        calc = new javax.swing.JButton();
        Call = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Payment");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(524, 20, 95, 34);

        Back.setBackground(new java.awt.Color(153, 153, 255));
        Back.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(102, 102, 255));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-arrow-30.png"))); // NOI18N
        Back.setText("BACK");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(10, 12, 103, 42);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(53, 91, 24, 21);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Payment Date:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(53, 160, 101, 21);

        ID.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel1.add(ID);
        ID.setBounds(186, 87, 104, 30);

        Pay_date.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel1.add(Pay_date);
        Pay_date.setBounds(172, 160, 162, 28);

        prod_price.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        prod_price.setForeground(new java.awt.Color(102, 102, 255));
        prod_price.setText("Product price:");
        jPanel1.add(prod_price);
        prod_price.setBounds(53, 236, 95, 21);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Total Amount:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(392, 164, 97, 21);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("Package amount:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(392, 80, 112, 21);

        mbrn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel1.add(mbrn);
        mbrn.setBounds(880, 80, 142, 28);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Valid Upto:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(392, 240, 76, 21);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 255));
        jLabel10.setText("Member name:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(770, 80, 100, 21);

        total_amt.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel1.add(total_amt);
        total_amt.setBounds(493, 160, 101, 30);

        Add.setBackground(new java.awt.Color(153, 153, 255));
        Add.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Add.setForeground(new java.awt.Color(102, 102, 255));
        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-24.png"))); // NOI18N
        Add.setText("ADD");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add);
        Add.setBounds(184, 314, 99, 34);

        Update.setBackground(new java.awt.Color(153, 153, 255));
        Update.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Update.setForeground(new java.awt.Color(102, 102, 255));
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-update-30.png"))); // NOI18N
        Update.setText("UPDATE");
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
        });
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update);
        Update.setBounds(326, 313, 123, 37);

        Delete.setBackground(new java.awt.Color(153, 153, 255));
        Delete.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Delete.setForeground(new java.awt.Color(102, 102, 255));
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-delete-30.png"))); // NOI18N
        Delete.setText("DELETE");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMouseExited(evt);
            }
        });
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete);
        Delete.setBounds(487, 311, 121, 41);

        PayTable.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        PayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Payment Date", "Product Price", "Package Amount", "Total Amount", "Valid Upto", "Member Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PayTable.getTableHeader().setReorderingAllowed(false);
        PayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PayTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PayTable);
        if (PayTable.getColumnModel().getColumnCount() > 0) {
            PayTable.getColumnModel().getColumn(0).setResizable(false);
            PayTable.getColumnModel().getColumn(1).setResizable(false);
            PayTable.getColumnModel().getColumn(2).setResizable(false);
            PayTable.getColumnModel().getColumn(3).setResizable(false);
            PayTable.getColumnModel().getColumn(4).setResizable(false);
            PayTable.getColumnModel().getColumn(5).setResizable(false);
            PayTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(18, 380, 1090, 287);

        View.setBackground(new java.awt.Color(153, 153, 255));
        View.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        View.setForeground(new java.awt.Color(102, 102, 255));
        View.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-view-30.png"))); // NOI18N
        View.setText("VIEW");
        View.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewMouseExited(evt);
            }
        });
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        jPanel1.add(View);
        View.setBounds(41, 313, 107, 37);

        pack_amt.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel1.add(pack_amt);
        pack_amt.setBounds(522, 76, 101, 30);

        Prod_price.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel1.add(Prod_price);
        Prod_price.setBounds(186, 236, 142, 30);

        Submit.setBackground(new java.awt.Color(153, 153, 255));
        Submit.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Submit.setForeground(new java.awt.Color(102, 102, 255));
        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-submit-resume-30.png"))); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitMouseExited(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit);
        Submit.setBounds(630, 310, 125, 41);

        valid_upto.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPanel1.add(valid_upto);
        valid_upto.setBounds(493, 238, 240, 28);

        bill.setBackground(new java.awt.Color(153, 153, 255));
        bill.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        bill.setForeground(new java.awt.Color(102, 102, 255));
        bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-bill-30.png"))); // NOI18N
        bill.setText("Generate Bill");
        bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billMouseExited(evt);
            }
        });
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });
        jPanel1.add(bill);
        bill.setBounds(780, 310, 157, 41);

        calc.setBackground(new java.awt.Color(153, 153, 255));
        calc.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        calc.setForeground(new java.awt.Color(102, 102, 255));
        calc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-plus-math-30.png"))); // NOI18N
        calc.setText("Calculate");
        calc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calcMouseExited(evt);
            }
        });
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });
        jPanel1.add(calc);
        calc.setBounds(604, 155, 129, 39);

        Call.setBackground(new java.awt.Color(153, 153, 255));
        Call.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Call.setForeground(new java.awt.Color(102, 102, 255));
        Call.setText("Call Procedure");
        Call.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallActionPerformed(evt);
            }
        });
        jPanel1.add(Call);
        Call.setBounds(960, 313, 140, 40);

        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/124358-download-gym-background.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1163, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1163, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        Back.setBackground(new Color(102,102,255));
        Back.setForeground(new Color(153,153,255));
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        Back.setBackground(new Color(153,153,255));
        Back.setForeground(new Color(102,102,255));
    }//GEN-LAST:event_BackMouseExited

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Package form= new Package();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        Add.setBackground(new Color(102,102,255));
        Add.setForeground(new Color(153,153,255));
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
        Add.setBackground(new Color(153,153,255));
        Add.setForeground(new Color(102,102,255));
    }//GEN-LAST:event_AddMouseExited

    private void UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseEntered
        Update.setBackground(new Color(102,102,255));
        Update.setForeground(new Color(153,153,255));
    }//GEN-LAST:event_UpdateMouseEntered

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
        Update.setBackground(new Color(153,153,255));
        Update.setForeground(new Color(102,102,255));
    }//GEN-LAST:event_UpdateMouseExited

    private void DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseEntered
        Delete.setBackground(new Color(102,102,255));
        Delete.setForeground(new Color(153,153,255));
    }//GEN-LAST:event_DeleteMouseEntered

    private void DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseExited
        Delete.setBackground(new Color(153,153,255));
        Delete.setForeground(new Color(102,102,255));
    }//GEN-LAST:event_DeleteMouseExited

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        String t=ID.getText();
        try{
        Connection con=MyConnection.getConnection();
        String sql="delete from payment where pay_id='"+t+"' ";
         PreparedStatement ps;
            ps=con.prepareStatement(sql);
            ps.execute();
             JOptionPane.showMessageDialog(this, "Payment Details deleted");
       }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed

    String id=ID.getText();
    String prodprice=Prod_price.getText();
    String packamt=pack_amt.getText();
    String totamt=total_amt.getText();
    String Mbrname=(String)mbrn.getSelectedItem();
    if(verifyText()){
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String paydate = dateFormat.format(Pay_date.getDate());
            String val = dateFormat.format(valid_upto.getDate());
            add a=new add();
            a.payment('i',id,paydate,prodprice,packamt,totamt,val,Mbrname);
        }
    }//GEN-LAST:event_AddActionPerformed

    
    
    private void fillmembername(){
        try {
            Connection con=MyConnection.getConnection();
            PreparedStatement ps;
            ps=con.prepareStatement("SELECT * FROM `members`");
            ResultSet rs=ps.executeQuery(); 
            while(rs.next()){
              String mbname=rs.getString("mbr_name");
              mbrn.addItem(mbname);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    public boolean verifyText(){
       if(ID.getText().equals("")||Prod_price.getText().equals("") ||pack_amt.getText().equals("")||Pay_date.getDate()==null||valid_upto.getDate()==null) {
           JOptionPane.showMessageDialog(null, "One or More fields is empty");
           return false;
       }
       else if(Pay_date.getDate().compareTo(new Date() )>0){
           JOptionPane.showMessageDialog(null, "Payment cannot be done in future");
           return false;
       }
       else{
           return true;
       }
        
      
   }
    private void ViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewMouseEntered
        View.setBackground(new Color(102,102,255));
        View.setForeground(new Color(153,153,255));
    }//GEN-LAST:event_ViewMouseEntered

    private void ViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewMouseExited
        View.setBackground(new Color(153,153,255));
        View.setForeground(new Color(102,102,255));
    }//GEN-LAST:event_ViewMouseExited

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        try {
            Connection con=MyConnection.getConnection();
            Statement st = con.createStatement();
            String mbr="select * from gym.payment";
            ResultSet rs=st.executeQuery(mbr);
            PayTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_ViewActionPerformed

    private void SubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseEntered
        Submit.setBackground(new Color(102,102,255));
        Submit.setForeground(new Color(153,153,255));
    }//GEN-LAST:event_SubmitMouseEntered

    private void SubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseExited
        Submit.setBackground(new Color(153,153,255));
        Submit.setForeground(new Color(102,102,255));
    }//GEN-LAST:event_SubmitMouseExited

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed

        JOptionPane.showMessageDialog(null, "Submitted");
        Homepage form= new Homepage();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_SubmitActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        try {
            String t=ID.getText();
            Connection con=MyConnection.getConnection();
            String sql="UPDATE `gym`.`payment` SET `pay_id` = ?,`pay_date` = ?,`prod_price` = ?,`pack_amt` = ?,tot_amt=?,`valid_upto` = ?,`mbr_name` = ? WHERE `pay_id` ='"+t+"'";
            PreparedStatement ps;
            ps=con.prepareStatement(sql);
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String pdate = dateFormat.format(Pay_date.getDate());
            String vu = dateFormat.format(valid_upto.getDate());
            String mbrname=(String)mbrn.getSelectedItem();
            ps.setString(1, ID.getText());
            ps.setString(2, pdate);
            ps.setString(3, Prod_price.getText());
            ps.setString(4, pack_amt.getText());
            ps.setString(5, total_amt.getText());
            ps.setString(6, vu);
            ps.setString(7, mbrname);
            ps.execute();
   
            JOptionPane.showMessageDialog(null, "Payment Details Updated");
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void PayTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayTableMouseClicked
        try {
            Connection con=MyConnection.getConnection();
            int row=PayTable.getSelectedRow();
            String tab=(PayTable.getModel().getValueAt(row,0).toString());
            String sql="SELECT * FROM gym.payment where pay_id='"+tab+"'";
            
            PreparedStatement ps;
            ps=con.prepareStatement(sql);
            ResultSet rs;
            rs=ps.executeQuery();
            if(rs.next()){
                String id=rs.getString("pay_id");
                ID.setText(id);
                Date pad=rs.getDate("pay_date");
                Pay_date.setDate(pad);
                String pamt=rs.getString("pack_amt");
                pack_amt.setText(pamt);
                String tamt=rs.getString("tot_amt");
                total_amt.setText(tamt);
                Date vu=rs.getDate("valid_upto");
                valid_upto.setDate(vu);
                String amount=rs.getString("prod_price");
                Prod_price.setText(amount);
                String mbrname=rs.getString("mbr_name");
                mbrn.setSelectedItem(mbrname);
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_PayTableMouseClicked

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        int row=PayTable.getSelectedRow();
        TableModel model=PayTable.getModel();
        String id=model.getValueAt(row,0).toString();
        String padate=model.getValueAt(row,1).toString();
        String prprice=model.getValueAt(row,2).toString();
        String pamt=model.getValueAt(row,3).toString();
        String tamt=model.getValueAt(row, 4).toString();
        String Vu=model.getValueAt(row,5).toString();
        String mname=model.getValueAt(row,6).toString();
        c.setVisible(true);
        c.pack();
        c.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        c.payid.setText(id);
        c.pdate.setText(padate);
        c.prodprice.setText(prprice);
        c.packamt.setText(pamt);
        c.totamt.setText(tamt);
        c.v.setText(Vu);
        c.mbrname.setText(mname);
    }//GEN-LAST:event_billActionPerformed

    private void billMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billMouseEntered
       bill.setBackground(new Color(102,102,255));
       bill.setForeground(new Color(153,153,255));
    }//GEN-LAST:event_billMouseEntered

    private void billMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billMouseExited
        bill.setBackground(new Color(153,153,255));
        bill.setForeground(new Color(102,102,255));
    }//GEN-LAST:event_billMouseExited

    private void calcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcMouseEntered
       calc.setBackground(new Color(102,102,255));
       calc.setForeground(new Color(153,153,255));
    }//GEN-LAST:event_calcMouseEntered

    private void calcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcMouseExited
        calc.setBackground(new Color(153,153,255));
        calc.setForeground(new Color(102,102,255));
    }//GEN-LAST:event_calcMouseExited

    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
        int a=Integer.parseInt(Prod_price.getText());
        int b=Integer.parseInt(pack_amt.getText());
        int c=a+b;
        total_amt.setText(c+"");
    }//GEN-LAST:event_calcActionPerformed

    private void CallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallActionPerformed
        try {
            Connection con=MyConnection.getConnection();
            CallableStatement cs=con.prepareCall("call calc_net_amt()");
            ResultSet rs=cs.executeQuery();
            PayTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_CallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Payment().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Back;
    private javax.swing.JButton Call;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField ID;
    public static javax.swing.JTable PayTable;
    private com.toedter.calendar.JDateChooser Pay_date;
    private javax.swing.JTextField Prod_price;
    private javax.swing.JButton Submit;
    private javax.swing.JButton Update;
    private javax.swing.JButton View;
    private javax.swing.JButton bill;
    private javax.swing.JButton calc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mbrn;
    private javax.swing.JTextField pack_amt;
    private javax.swing.JLabel prod_price;
    private javax.swing.JTextField total_amt;
    private com.toedter.calendar.JDateChooser valid_upto;
    // End of variables declaration//GEN-END:variables
}
